# Generated by Django 4.2.20 on 2025-03-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_menuitem_table_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='check_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
