# Generated by Django 4.2.20 on 2025-03-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_table_check_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='table',
            name='check_number',
            field=models.PositiveIntegerField(),
        ),
    ]
