# Generated by Django 4.2.20 on 2025-03-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_checkhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkhistory',
            name='items_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
